[build]
  base = "frontend"
  command = "rm -rf node_modules package-lock.json .npm .cache .angular && npm cache clean --force && npm install --no-package-lock --force --legacy-peer-deps --no-audit && npm run build"
  publish = "dist/frontend/browser"

[functions]
  directory = "../functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16" 
