[build]
  base = "frontend"
  command = "rm -rf node_modules package-lock.json .npm .cache .angular dist && npm cache clean --force && npm install --no-package-lock --force --legacy-peer-deps --no-audit --prefer-offline=false --no-optional && npx @angular/cli@11.2.0 build --configuration production"
  publish = "dist/frontend"

[functions]
  directory = "../functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "14.15.0" 
